package com.example.hospitalcompose.common

object Constantes {
    const val ERROR_EN_LA_CONVERSION = "Error en la conversión"
    const val LOGIN_EXITOSO = "Login exitoso"
    const val ERROR_DESCONOCIDO = "Error desconocido"
    const val ERROR_DESCONOCIDO_EN_EL_LOGIN = "Error desconocido en el login"
    const val CAMPO_NOMBRE = "Nombre"
    const val CAMPO_OSCAR_MEJOR_DIRECTOR = "Óscar Mejor Director"
    const val CAMPO_NUMERO_PELICULAS = "Número de Películas"
    const val BOTON_ACTUALIZAR = "Actualizar"
    const val BOTON_ELIMINAR = "Eliminar"
    const val BOTON_ANADIR = "Añadir"
    const val DIRECTOR_ACTUALIZADO = "Director actualizado"
    const val ERROR_ACTUALIZAR = "Error al actualizar"
    const val DIRECTOR_ANADIDO = "Director añadido"
    const val ERROR_ANADIR_DIRECTOR = "Error al añadir director"
    const val DIRECTOR_ELIMINADO = "Director eliminado"
    const val ERROR_ELIMINAR = "Error al eliminar"
    const val ETIQUETA_OSCARS = "Óscars: "
    const val ETIQUETA_PELICULAS = "Películas dirigidas: "
    const val ERROR_CARGAR_DIRECTORES = "Error al cargar directores"
    const val TITULO_INICIAR_SESION = "Iniciar Sesión"
    const val TITULO_REGISTRO = "Registro"
    const val LABEL_USUARIO = "Usuario"
    const val LABEL_CONTRASENA = "Contraseña"
    const val LABEL_CORREO_ELECTRONICO = "Correo Electrónico"
    const val BOTON_INICIAR_SESION = "Iniciar Sesión"
    const val BOTON_REGISTRARSE = "Registrarse"
    const val CREDENCIALES_INCORRECTAS = "Credenciales Incorrectas"
    const val REGISTRO_EXITOSO = "Registro exitoso"
    const val LABEL_TITULO = "Título"
    const val LABEL_ANIO = "Año"
    const val LABEL_DIRECTOR = "Director"
    const val LABEL_DESCRIPCION = "Descripción"
    const val PELICULA_ACTUALIZADA = "Película actualizada"
    const val ERROR_ACTUALIZAR_PELICULA = "Error al actualizar"
    const val PELICULA_ANADIDA = "Película añadida"
    const val ERROR_ANADIR_PELICULA = "Error al añadir película"
    const val PELICULA_ELIMINADA = "Película eliminada"
    const val ERROR_ELIMINAR_PELICULA = "Error al eliminar"
    const val LOGIN = "Login"
    const val LOCALIZED_DESCRIPTION = "Localized description"
    const val PELICULAS = "Peliculas"
    const val CANCIONES = "Canciones"
    const val GRABADORA = "Grabadora"
    const val AFINADOR = "Afinador"
    const val RITMOS = "Ritmos"


}
