name: Java CI with Maven and Docker

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - '.github/workflows/java.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - '.github/workflows/java.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MAJOR_VERSION: ${{ vars.JAVA_MAJOR_VERSION || '1' }}
      MINOR_VERSION: ${{ vars.JAVA_MINOR_VERSION || '0' }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven (sin tests)
      run: mvn -B package --file pom.xml -DskipTests

    - name: Check code quality
      run: |
        mvn compile
        echo "Verificación de calidad de código completada"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: diegopachecoolivares
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set version
      id: version
      run: echo "VERSION=${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ github.run_number }}" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          diegopachecoolivares/devtoksapi:latest
          diegopachecoolivares/devtoksapi:${{ steps.version.outputs.VERSION }}